insert into competitions values('Premier League',1900,'Arsenal','league');
insert into competitions values('FA Cup',1900,'Bournemouth','cup');
insert into competitions values('EFL Cup',1900,'Stoke','cup');
insert into competitions values('Champions League',1900,'Southampton','cup');
insert into competitions values('Premier League',1901,'Sunderland','league');
insert into competitions values('FA Cup',1901,'Man United','cup');
insert into competitions values('EFL Cup',1901,'Liverpool','cup');
insert into competitions values('Champions League',1901,'Burnley','cup');
insert into competitions values('Premier League',1902,'Stoke','league');
insert into competitions values('FA Cup',1902,'Leicester','cup');
insert into competitions values('EFL Cup',1902,'Southampton','cup');
insert into competitions values('Champions League',1902,'Tottenham','cup');
insert into competitions values('Premier League',1903,'Tottenham','league');
insert into competitions values('FA Cup',1903,'Sunderland','cup');
insert into competitions values('EFL Cup',1903,'Southampton','cup');
insert into competitions values('Champions League',1903,'Burnley','cup');
insert into competitions values('Premier League',1904,'Liverpool','league');
insert into competitions values('FA Cup',1904,'Leicester','cup');
insert into competitions values('EFL Cup',1904,'Watford','cup');
insert into competitions values('Champions League',1904,'Sunderland','cup');
insert into competitions values('Premier League',1905,'Bournemouth','league');
insert into competitions values('FA Cup',1905,'Everton','cup');
insert into competitions values('EFL Cup',1905,'Southampton','cup');
insert into competitions values('Champions League',1905,'West Brom','cup');
insert into competitions values('Premier League',1906,'Watford','league');
insert into competitions values('FA Cup',1906,'Man United','cup');
insert into competitions values('EFL Cup',1906,'Chelsea','cup');
insert into competitions values('Champions League',1906,'West Ham','cup');
insert into competitions values('Premier League',1907,'Swansea','league');
insert into competitions values('FA Cup',1907,'Man United','cup');
insert into competitions values('EFL Cup',1907,'Burnley','cup');
insert into competitions values('Champions League',1907,'Man City','cup');
insert into competitions values('Premier League',1908,'Man City','league');
insert into competitions values('FA Cup',1908,'Middlesbrough','cup');
insert into competitions values('EFL Cup',1908,'Hull','cup');
insert into competitions values('Champions League',1908,'West Ham','cup');
insert into competitions values('Premier League',1909,'Leicester','league');
insert into competitions values('FA Cup',1909,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1909,'Arsenal','cup');
insert into competitions values('Champions League',1909,'Middlesbrough','cup');
insert into competitions values('Premier League',1910,'Stoke','league');
insert into competitions values('FA Cup',1910,'Arsenal','cup');
insert into competitions values('EFL Cup',1910,'Burnley','cup');
insert into competitions values('Champions League',1910,'Swansea','cup');
insert into competitions values('Premier League',1911,'West Ham','league');
insert into competitions values('FA Cup',1911,'Sunderland','cup');
insert into competitions values('EFL Cup',1911,'Arsenal','cup');
insert into competitions values('Champions League',1911,'Middlesbrough','cup');
insert into competitions values('Premier League',1912,'Middlesbrough','league');
insert into competitions values('FA Cup',1912,'Burnley','cup');
insert into competitions values('EFL Cup',1912,'Southampton','cup');
insert into competitions values('Champions League',1912,'West Ham','cup');
insert into competitions values('Premier League',1913,'West Ham','league');
insert into competitions values('FA Cup',1913,'Leicester','cup');
insert into competitions values('EFL Cup',1913,'Chelsea','cup');
insert into competitions values('Champions League',1913,'Sunderland','cup');
insert into competitions values('Premier League',1914,'Sunderland','league');
insert into competitions values('FA Cup',1914,'Stoke','cup');
insert into competitions values('EFL Cup',1914,'Tottenham','cup');
insert into competitions values('Champions League',1914,'Everton','cup');
insert into competitions values('Premier League',1915,'Leicester','league');
insert into competitions values('FA Cup',1915,'Swansea','cup');
insert into competitions values('EFL Cup',1915,'Liverpool','cup');
insert into competitions values('Champions League',1915,'Man City','cup');
insert into competitions values('Premier League',1916,'Stoke','league');
insert into competitions values('FA Cup',1916,'Man City','cup');
insert into competitions values('EFL Cup',1916,'Man City','cup');
insert into competitions values('Champions League',1916,'Swansea','cup');
insert into competitions values('Premier League',1917,'Man City','league');
insert into competitions values('FA Cup',1917,'Liverpool','cup');
insert into competitions values('EFL Cup',1917,'Middlesbrough','cup');
insert into competitions values('Champions League',1917,'West Brom','cup');
insert into competitions values('Premier League',1918,'Crystal Palace','league');
insert into competitions values('FA Cup',1918,'Hull','cup');
insert into competitions values('EFL Cup',1918,'Stoke','cup');
insert into competitions values('Champions League',1918,'Stoke','cup');
insert into competitions values('Premier League',1919,'Arsenal','league');
insert into competitions values('FA Cup',1919,'Everton','cup');
insert into competitions values('EFL Cup',1919,'Southampton','cup');
insert into competitions values('Champions League',1919,'Liverpool','cup');
insert into competitions values('Premier League',1920,'Southampton','league');
insert into competitions values('FA Cup',1920,'Southampton','cup');
insert into competitions values('EFL Cup',1920,'Southampton','cup');
insert into competitions values('Champions League',1920,'Arsenal','cup');
insert into competitions values('Premier League',1921,'Everton','league');
insert into competitions values('FA Cup',1921,'Bournemouth','cup');
insert into competitions values('EFL Cup',1921,'Chelsea','cup');
insert into competitions values('Champions League',1921,'West Brom','cup');
insert into competitions values('Premier League',1922,'Bournemouth','league');
insert into competitions values('FA Cup',1922,'Middlesbrough','cup');
insert into competitions values('EFL Cup',1922,'Man United','cup');
insert into competitions values('Champions League',1922,'West Ham','cup');
insert into competitions values('Premier League',1923,'Swansea','league');
insert into competitions values('FA Cup',1923,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1923,'Southampton','cup');
insert into competitions values('Champions League',1923,'Chelsea','cup');
insert into competitions values('Premier League',1924,'Chelsea','league');
insert into competitions values('FA Cup',1924,'Arsenal','cup');
insert into competitions values('EFL Cup',1924,'Sunderland','cup');
insert into competitions values('Champions League',1924,'Man United','cup');
insert into competitions values('Premier League',1925,'Liverpool','league');
insert into competitions values('FA Cup',1925,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1925,'Burnley','cup');
insert into competitions values('Champions League',1925,'Tottenham','cup');
insert into competitions values('Premier League',1926,'West Ham','league');
insert into competitions values('FA Cup',1926,'Stoke','cup');
insert into competitions values('EFL Cup',1926,'Chelsea','cup');
insert into competitions values('Champions League',1926,'Bournemouth','cup');
insert into competitions values('Premier League',1927,'Crystal Palace','league');
insert into competitions values('FA Cup',1927,'Man United','cup');
insert into competitions values('EFL Cup',1927,'Bournemouth','cup');
insert into competitions values('Champions League',1927,'Crystal Palace','cup');
insert into competitions values('Premier League',1928,'Everton','league');
insert into competitions values('FA Cup',1928,'Stoke','cup');
insert into competitions values('EFL Cup',1928,'West Brom','cup');
insert into competitions values('Champions League',1928,'Bournemouth','cup');
insert into competitions values('Premier League',1929,'Swansea','league');
insert into competitions values('FA Cup',1929,'Burnley','cup');
insert into competitions values('EFL Cup',1929,'Sunderland','cup');
insert into competitions values('Champions League',1929,'Chelsea','cup');
insert into competitions values('Premier League',1930,'Burnley','league');
insert into competitions values('FA Cup',1930,'Watford','cup');
insert into competitions values('EFL Cup',1930,'Man City','cup');
insert into competitions values('Champions League',1930,'Middlesbrough','cup');
insert into competitions values('Premier League',1931,'Swansea','league');
insert into competitions values('FA Cup',1931,'Sunderland','cup');
insert into competitions values('EFL Cup',1931,'Leicester','cup');
insert into competitions values('Champions League',1931,'West Ham','cup');
insert into competitions values('Premier League',1932,'Stoke','league');
insert into competitions values('FA Cup',1932,'Liverpool','cup');
insert into competitions values('EFL Cup',1932,'West Ham','cup');
insert into competitions values('Champions League',1932,'West Ham','cup');
insert into competitions values('Premier League',1933,'Stoke','league');
insert into competitions values('FA Cup',1933,'Burnley','cup');
insert into competitions values('EFL Cup',1933,'Stoke','cup');
insert into competitions values('Champions League',1933,'Man City','cup');
insert into competitions values('Premier League',1934,'Middlesbrough','league');
insert into competitions values('FA Cup',1934,'West Ham','cup');
insert into competitions values('EFL Cup',1934,'West Brom','cup');
insert into competitions values('Champions League',1934,'Stoke','cup');
insert into competitions values('Premier League',1935,'Hull','league');
insert into competitions values('FA Cup',1935,'Everton','cup');
insert into competitions values('EFL Cup',1935,'Leicester','cup');
insert into competitions values('Champions League',1935,'Liverpool','cup');
insert into competitions values('Premier League',1936,'Tottenham','league');
insert into competitions values('FA Cup',1936,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1936,'Middlesbrough','cup');
insert into competitions values('Champions League',1936,'Leicester','cup');
insert into competitions values('Premier League',1937,'Southampton','league');
insert into competitions values('FA Cup',1937,'Sunderland','cup');
insert into competitions values('EFL Cup',1937,'Burnley','cup');
insert into competitions values('Champions League',1937,'Tottenham','cup');
insert into competitions values('Premier League',1938,'Everton','league');
insert into competitions values('FA Cup',1938,'Chelsea','cup');
insert into competitions values('EFL Cup',1938,'Chelsea','cup');
insert into competitions values('Champions League',1938,'Tottenham','cup');
insert into competitions values('Premier League',1939,'Liverpool','league');
insert into competitions values('FA Cup',1939,'Leicester','cup');
insert into competitions values('EFL Cup',1939,'Arsenal','cup');
insert into competitions values('Champions League',1939,'Arsenal','cup');
insert into competitions values('Premier League',1940,'Everton','league');
insert into competitions values('FA Cup',1940,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1940,'Watford','cup');
insert into competitions values('Champions League',1940,'Stoke','cup');
insert into competitions values('Premier League',1941,'Leicester','league');
insert into competitions values('FA Cup',1941,'Sunderland','cup');
insert into competitions values('EFL Cup',1941,'Chelsea','cup');
insert into competitions values('Champions League',1941,'Arsenal','cup');
insert into competitions values('Premier League',1942,'Hull','league');
insert into competitions values('FA Cup',1942,'West Brom','cup');
insert into competitions values('EFL Cup',1942,'Crystal Palace','cup');
insert into competitions values('Champions League',1942,'Liverpool','cup');
insert into competitions values('Premier League',1943,'Chelsea','league');
insert into competitions values('FA Cup',1943,'Man United','cup');
insert into competitions values('EFL Cup',1943,'Bournemouth','cup');
insert into competitions values('Champions League',1943,'Swansea','cup');
insert into competitions values('Premier League',1944,'West Ham','league');
insert into competitions values('FA Cup',1944,'Chelsea','cup');
insert into competitions values('EFL Cup',1944,'Liverpool','cup');
insert into competitions values('Champions League',1944,'Southampton','cup');
insert into competitions values('Premier League',1945,'Crystal Palace','league');
insert into competitions values('FA Cup',1945,'West Brom','cup');
insert into competitions values('EFL Cup',1945,'Leicester','cup');
insert into competitions values('Champions League',1945,'Burnley','cup');
insert into competitions values('Premier League',1946,'Watford','league');
insert into competitions values('FA Cup',1946,'Man City','cup');
insert into competitions values('EFL Cup',1946,'Stoke','cup');
insert into competitions values('Champions League',1946,'Burnley','cup');
insert into competitions values('Premier League',1947,'Everton','league');
insert into competitions values('FA Cup',1947,'Everton','cup');
insert into competitions values('EFL Cup',1947,'Crystal Palace','cup');
insert into competitions values('Champions League',1947,'Hull','cup');
insert into competitions values('Premier League',1948,'Crystal Palace','league');
insert into competitions values('FA Cup',1948,'Everton','cup');
insert into competitions values('EFL Cup',1948,'Man City','cup');
insert into competitions values('Champions League',1948,'Burnley','cup');
insert into competitions values('Premier League',1949,'West Brom','league');
insert into competitions values('FA Cup',1949,'Hull','cup');
insert into competitions values('EFL Cup',1949,'Watford','cup');
insert into competitions values('Champions League',1949,'Everton','cup');
insert into competitions values('Premier League',1950,'Bournemouth','league');
insert into competitions values('FA Cup',1950,'Swansea','cup');
insert into competitions values('EFL Cup',1950,'Tottenham','cup');
insert into competitions values('Champions League',1950,'Hull','cup');
insert into competitions values('Premier League',1951,'Hull','league');
insert into competitions values('FA Cup',1951,'Man United','cup');
insert into competitions values('EFL Cup',1951,'Crystal Palace','cup');
insert into competitions values('Champions League',1951,'Burnley','cup');
insert into competitions values('Premier League',1952,'Leicester','league');
insert into competitions values('FA Cup',1952,'Arsenal','cup');
insert into competitions values('EFL Cup',1952,'Middlesbrough','cup');
insert into competitions values('Champions League',1952,'Everton','cup');
insert into competitions values('Premier League',1953,'Southampton','league');
insert into competitions values('FA Cup',1953,'Watford','cup');
insert into competitions values('EFL Cup',1953,'Swansea','cup');
insert into competitions values('Champions League',1953,'Liverpool','cup');
insert into competitions values('Premier League',1954,'Liverpool','league');
insert into competitions values('FA Cup',1954,'West Brom','cup');
insert into competitions values('EFL Cup',1954,'Liverpool','cup');
insert into competitions values('Champions League',1954,'Everton','cup');
insert into competitions values('Premier League',1955,'Middlesbrough','league');
insert into competitions values('FA Cup',1955,'West Ham','cup');
insert into competitions values('EFL Cup',1955,'Middlesbrough','cup');
insert into competitions values('Champions League',1955,'Burnley','cup');
insert into competitions values('Premier League',1956,'Sunderland','league');
insert into competitions values('FA Cup',1956,'Chelsea','cup');
insert into competitions values('EFL Cup',1956,'Hull','cup');
insert into competitions values('Champions League',1956,'Everton','cup');
insert into competitions values('Premier League',1957,'Swansea','league');
insert into competitions values('FA Cup',1957,'Liverpool','cup');
insert into competitions values('EFL Cup',1957,'Swansea','cup');
insert into competitions values('Champions League',1957,'Man United','cup');
insert into competitions values('Premier League',1958,'Arsenal','league');
insert into competitions values('FA Cup',1958,'Hull','cup');
insert into competitions values('EFL Cup',1958,'West Ham','cup');
insert into competitions values('Champions League',1958,'West Ham','cup');
insert into competitions values('Premier League',1959,'Leicester','league');
insert into competitions values('FA Cup',1959,'Chelsea','cup');
insert into competitions values('EFL Cup',1959,'Liverpool','cup');
insert into competitions values('Champions League',1959,'Crystal Palace','cup');
insert into competitions values('Premier League',1960,'Tottenham','league');
insert into competitions values('FA Cup',1960,'Liverpool','cup');
insert into competitions values('EFL Cup',1960,'Man United','cup');
insert into competitions values('Champions League',1960,'West Brom','cup');
insert into competitions values('Premier League',1961,'West Ham','league');
insert into competitions values('FA Cup',1961,'West Ham','cup');
insert into competitions values('EFL Cup',1961,'Chelsea','cup');
insert into competitions values('Champions League',1961,'Swansea','cup');
insert into competitions values('Premier League',1962,'Southampton','league');
insert into competitions values('FA Cup',1962,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1962,'West Ham','cup');
insert into competitions values('Champions League',1962,'Bournemouth','cup');
insert into competitions values('Premier League',1963,'Bournemouth','league');
insert into competitions values('FA Cup',1963,'Man United','cup');
insert into competitions values('EFL Cup',1963,'Everton','cup');
insert into competitions values('Champions League',1963,'Liverpool','cup');
insert into competitions values('Premier League',1964,'Middlesbrough','league');
insert into competitions values('FA Cup',1964,'Hull','cup');
insert into competitions values('EFL Cup',1964,'Tottenham','cup');
insert into competitions values('Champions League',1964,'West Brom','cup');
insert into competitions values('Premier League',1965,'Everton','league');
insert into competitions values('FA Cup',1965,'Tottenham','cup');
insert into competitions values('EFL Cup',1965,'Southampton','cup');
insert into competitions values('Champions League',1965,'Arsenal','cup');
insert into competitions values('Premier League',1966,'Swansea','league');
insert into competitions values('FA Cup',1966,'Leicester','cup');
insert into competitions values('EFL Cup',1966,'Leicester','cup');
insert into competitions values('Champions League',1966,'Middlesbrough','cup');
insert into competitions values('Premier League',1967,'Swansea','league');
insert into competitions values('FA Cup',1967,'Liverpool','cup');
insert into competitions values('EFL Cup',1967,'Crystal Palace','cup');
insert into competitions values('Champions League',1967,'Hull','cup');
insert into competitions values('Premier League',1968,'Burnley','league');
insert into competitions values('FA Cup',1968,'Swansea','cup');
insert into competitions values('EFL Cup',1968,'Crystal Palace','cup');
insert into competitions values('Champions League',1968,'Southampton','cup');
insert into competitions values('Premier League',1969,'Watford','league');
insert into competitions values('FA Cup',1969,'Liverpool','cup');
insert into competitions values('EFL Cup',1969,'Sunderland','cup');
insert into competitions values('Champions League',1969,'Man United','cup');
insert into competitions values('Premier League',1970,'Middlesbrough','league');
insert into competitions values('FA Cup',1970,'Watford','cup');
insert into competitions values('EFL Cup',1970,'Sunderland','cup');
insert into competitions values('Champions League',1970,'Man United','cup');
insert into competitions values('Premier League',1971,'Leicester','league');
insert into competitions values('FA Cup',1971,'Watford','cup');
insert into competitions values('EFL Cup',1971,'Stoke','cup');
insert into competitions values('Champions League',1971,'West Ham','cup');
insert into competitions values('Premier League',1972,'Chelsea','league');
insert into competitions values('FA Cup',1972,'Sunderland','cup');
insert into competitions values('EFL Cup',1972,'West Ham','cup');
insert into competitions values('Champions League',1972,'Stoke','cup');
insert into competitions values('Premier League',1973,'Watford','league');
insert into competitions values('FA Cup',1973,'Southampton','cup');
insert into competitions values('EFL Cup',1973,'Man City','cup');
insert into competitions values('Champions League',1973,'Stoke','cup');
insert into competitions values('Premier League',1974,'Burnley','league');
insert into competitions values('FA Cup',1974,'Man City','cup');
insert into competitions values('EFL Cup',1974,'Watford','cup');
insert into competitions values('Champions League',1974,'Burnley','cup');
insert into competitions values('Premier League',1975,'Stoke','league');
insert into competitions values('FA Cup',1975,'West Brom','cup');
insert into competitions values('EFL Cup',1975,'Bournemouth','cup');
insert into competitions values('Champions League',1975,'Middlesbrough','cup');
insert into competitions values('Premier League',1976,'Everton','league');
insert into competitions values('FA Cup',1976,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1976,'Sunderland','cup');
insert into competitions values('Champions League',1976,'Bournemouth','cup');
insert into competitions values('Premier League',1977,'Chelsea','league');
insert into competitions values('FA Cup',1977,'Watford','cup');
insert into competitions values('EFL Cup',1977,'Burnley','cup');
insert into competitions values('Champions League',1977,'Hull','cup');
insert into competitions values('Premier League',1978,'Swansea','league');
insert into competitions values('FA Cup',1978,'Man City','cup');
insert into competitions values('EFL Cup',1978,'Watford','cup');
insert into competitions values('Champions League',1978,'Southampton','cup');
insert into competitions values('Premier League',1979,'Sunderland','league');
insert into competitions values('FA Cup',1979,'Southampton','cup');
insert into competitions values('EFL Cup',1979,'Chelsea','cup');
insert into competitions values('Champions League',1979,'Arsenal','cup');
insert into competitions values('Premier League',1980,'Burnley','league');
insert into competitions values('FA Cup',1980,'Burnley','cup');
insert into competitions values('EFL Cup',1980,'Middlesbrough','cup');
insert into competitions values('Champions League',1980,'Man United','cup');
insert into competitions values('Premier League',1981,'West Brom','league');
insert into competitions values('FA Cup',1981,'West Brom','cup');
insert into competitions values('EFL Cup',1981,'Bournemouth','cup');
insert into competitions values('Champions League',1981,'Man City','cup');
insert into competitions values('Premier League',1982,'Crystal Palace','league');
insert into competitions values('FA Cup',1982,'Sunderland','cup');
insert into competitions values('EFL Cup',1982,'West Brom','cup');
insert into competitions values('Champions League',1982,'Crystal Palace','cup');
insert into competitions values('Premier League',1983,'Sunderland','league');
insert into competitions values('FA Cup',1983,'Middlesbrough','cup');
insert into competitions values('EFL Cup',1983,'West Ham','cup');
insert into competitions values('Champions League',1983,'Southampton','cup');
insert into competitions values('Premier League',1984,'Bournemouth','league');
insert into competitions values('FA Cup',1984,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1984,'Sunderland','cup');
insert into competitions values('Champions League',1984,'West Ham','cup');
insert into competitions values('Premier League',1985,'Everton','league');
insert into competitions values('FA Cup',1985,'Bournemouth','cup');
insert into competitions values('EFL Cup',1985,'Southampton','cup');
insert into competitions values('Champions League',1985,'West Ham','cup');
insert into competitions values('Premier League',1986,'Bournemouth','league');
insert into competitions values('FA Cup',1986,'Burnley','cup');
insert into competitions values('EFL Cup',1986,'Liverpool','cup');
insert into competitions values('Champions League',1986,'West Ham','cup');
insert into competitions values('Premier League',1987,'Burnley','league');
insert into competitions values('FA Cup',1987,'West Ham','cup');
insert into competitions values('EFL Cup',1987,'Stoke','cup');
insert into competitions values('Champions League',1987,'Man United','cup');
insert into competitions values('Premier League',1988,'Crystal Palace','league');
insert into competitions values('FA Cup',1988,'West Ham','cup');
insert into competitions values('EFL Cup',1988,'Tottenham','cup');
insert into competitions values('Champions League',1988,'Arsenal','cup');
insert into competitions values('Premier League',1989,'Watford','league');
insert into competitions values('FA Cup',1989,'Everton','cup');
insert into competitions values('EFL Cup',1989,'Watford','cup');
insert into competitions values('Champions League',1989,'Leicester','cup');
insert into competitions values('Premier League',1990,'Leicester','league');
insert into competitions values('FA Cup',1990,'Southampton','cup');
insert into competitions values('EFL Cup',1990,'Bournemouth','cup');
insert into competitions values('Champions League',1990,'Man City','cup');
insert into competitions values('Premier League',1991,'Watford','league');
insert into competitions values('FA Cup',1991,'Hull','cup');
insert into competitions values('EFL Cup',1991,'Bournemouth','cup');
insert into competitions values('Champions League',1991,'Everton','cup');
insert into competitions values('Premier League',1992,'Hull','league');
insert into competitions values('FA Cup',1992,'Tottenham','cup');
insert into competitions values('EFL Cup',1992,'Bournemouth','cup');
insert into competitions values('Champions League',1992,'Liverpool','cup');
insert into competitions values('Premier League',1993,'Man City','league');
insert into competitions values('FA Cup',1993,'Crystal Palace','cup');
insert into competitions values('EFL Cup',1993,'Southampton','cup');
insert into competitions values('Champions League',1993,'Arsenal','cup');
insert into competitions values('Premier League',1994,'Watford','league');
insert into competitions values('FA Cup',1994,'Burnley','cup');
insert into competitions values('EFL Cup',1994,'Swansea','cup');
insert into competitions values('Champions League',1994,'West Ham','cup');
insert into competitions values('Premier League',1995,'Stoke','league');
insert into competitions values('FA Cup',1995,'West Ham','cup');
insert into competitions values('EFL Cup',1995,'Man City','cup');
insert into competitions values('Champions League',1995,'Hull','cup');
insert into competitions values('Premier League',1996,'Watford','league');
insert into competitions values('FA Cup',1996,'Man City','cup');
insert into competitions values('EFL Cup',1996,'West Ham','cup');
insert into competitions values('Champions League',1996,'Stoke','cup');
insert into competitions values('Premier League',1997,'Stoke','league');
insert into competitions values('FA Cup',1997,'Watford','cup');
insert into competitions values('EFL Cup',1997,'Stoke','cup');
insert into competitions values('Champions League',1997,'Arsenal','cup');
insert into competitions values('Premier League',1998,'Stoke','league');
insert into competitions values('FA Cup',1998,'Swansea','cup');
insert into competitions values('EFL Cup',1998,'Burnley','cup');
insert into competitions values('Champions League',1998,'Everton','cup');
insert into competitions values('Premier League',1999,'Sunderland','league');
insert into competitions values('FA Cup',1999,'Middlesbrough','cup');
insert into competitions values('EFL Cup',1999,'Tottenham','cup');
insert into competitions values('Champions League',1999,'Stoke','cup');
insert into competitions values('Premier League',2000,'Swansea','league');
insert into competitions values('FA Cup',2000,'Everton','cup');
insert into competitions values('EFL Cup',2000,'Southampton','cup');
insert into competitions values('Champions League',2000,'Watford','cup');
insert into competitions values('Premier League',2001,'Man City','league');
insert into competitions values('FA Cup',2001,'Sunderland','cup');
insert into competitions values('EFL Cup',2001,'Everton','cup');
insert into competitions values('Champions League',2001,'Stoke','cup');
insert into competitions values('Premier League',2002,'Chelsea','league');
insert into competitions values('FA Cup',2002,'Middlesbrough','cup');
insert into competitions values('EFL Cup',2002,'Middlesbrough','cup');
insert into competitions values('Champions League',2002,'Liverpool','cup');
insert into competitions values('Premier League',2003,'Everton','league');
insert into competitions values('FA Cup',2003,'West Ham','cup');
insert into competitions values('EFL Cup',2003,'Southampton','cup');
insert into competitions values('Champions League',2003,'Chelsea','cup');
insert into competitions values('Premier League',2004,'Crystal Palace','league');
insert into competitions values('FA Cup',2004,'Liverpool','cup');
insert into competitions values('EFL Cup',2004,'Leicester','cup');
insert into competitions values('Champions League',2004,'Tottenham','cup');
insert into competitions values('Premier League',2005,'Hull','league');
insert into competitions values('FA Cup',2005,'Middlesbrough','cup');
insert into competitions values('EFL Cup',2005,'Man City','cup');
insert into competitions values('Champions League',2005,'Leicester','cup');
insert into competitions values('Premier League',2006,'Arsenal','league');
insert into competitions values('FA Cup',2006,'Watford','cup');
insert into competitions values('EFL Cup',2006,'Watford','cup');
insert into competitions values('Champions League',2006,'Southampton','cup');
insert into competitions values('Premier League',2007,'Sunderland','league');
insert into competitions values('FA Cup',2007,'Swansea','cup');
insert into competitions values('EFL Cup',2007,'Swansea','cup');
insert into competitions values('Champions League',2007,'Crystal Palace','cup');
insert into competitions values('Premier League',2008,'West Brom','league');
insert into competitions values('FA Cup',2008,'Man United','cup');
insert into competitions values('EFL Cup',2008,'Sunderland','cup');
insert into competitions values('Champions League',2008,'Leicester','cup');
insert into competitions values('Premier League',2009,'Stoke','league');
insert into competitions values('FA Cup',2009,'Arsenal','cup');
insert into competitions values('EFL Cup',2009,'Arsenal','cup');
insert into competitions values('Champions League',2009,'Swansea','cup');
insert into competitions values('Premier League',2010,'Leicester','league');
insert into competitions values('FA Cup',2010,'Middlesbrough','cup');
insert into competitions values('EFL Cup',2010,'Swansea','cup');
insert into competitions values('Champions League',2010,'West Brom','cup');
insert into competitions values('Premier League',2011,'Burnley','league');
insert into competitions values('FA Cup',2011,'West Ham','cup');
insert into competitions values('EFL Cup',2011,'Watford','cup');
insert into competitions values('Champions League',2011,'Hull','cup');
insert into competitions values('Premier League',2012,'Chelsea','league');
insert into competitions values('FA Cup',2012,'Southampton','cup');
insert into competitions values('EFL Cup',2012,'Tottenham','cup');
insert into competitions values('Champions League',2012,'Bournemouth','cup');
insert into competitions values('Premier League',2013,'Stoke','league');
insert into competitions values('FA Cup',2013,'Hull','cup');
insert into competitions values('EFL Cup',2013,'Southampton','cup');
insert into competitions values('Champions League',2013,'Stoke','cup');
insert into competitions values('Premier League',2014,'Sunderland','league');
insert into competitions values('FA Cup',2014,'Tottenham','cup');
insert into competitions values('EFL Cup',2014,'Sunderland','cup');
insert into competitions values('Champions League',2014,'Burnley','cup');
insert into competitions values('Premier League',2015,'Liverpool','league');
insert into competitions values('FA Cup',2015,'Watford','cup');
insert into competitions values('EFL Cup',2015,'Arsenal','cup');
insert into competitions values('Champions League',2015,'Chelsea','cup');
insert into competitions values('Premier League',2016,'Everton','league');
insert into competitions values('FA Cup',2016,'Bournemouth','cup');
insert into competitions values('EFL Cup',2016,'Chelsea','cup');
insert into competitions values('Champions League',2016,'Liverpool','cup');
