--Teams
insert into teams values('Arsenal', 1886, 'Emirates Stadium', 'Stan Kroenke');
insert into teams values('AFC Bournemouth', 1899, 'Dean Court', 'Maxim Demin');
insert into teams values('Burnley', 1882, 'Turf Moor', 'Mike Garlick');
insert into teams values('Chelsea', 1905, 'Stamford Bridge', 'Roman Abramovich');
insert into teams values('Crystal Palace', 1905, 'Selhurst Park', 'Steve Parish');
insert into teams values('Everton', 1878, 'Goodison Park', 'Farhad Moshiri');
insert into teams values('Hull City', 1904, 'KCOM Stadium', 'Assem Allam');
insert into teams values('Leicester City', 1884, 'King Power Stadium', 'King Power International Group');
insert into teams values('Liverpool', 1892, 'Anfield', 'Fenway Sports Group');
insert into teams values('Manchester City', 1880, 'City of Manchester Stadium', 'City Football Group');

--Arsenal players
insert into players values('David Ospina', 13, 'Arsenal', 'Colombia', 'GoalKeeper');
insert into players values('Petr Cech', 33, 'Arsenal', 'Czech Republic', 'GoalKeeper');
insert into players values('Emiliano Martinez', 26, 'Arsenal', 'Argentina', 'GoalKeeper');
insert into players values('Mathieu Debuchy', 2, 'Arsenal', 'France', 'Defender');
insert into players values('Kieran Gibbs', 3, 'Arsenal', 'England', 'Defender');
insert into players values('Per Mertesacker', 4, 'Arsenal', 'Germany', 'Defender');
insert into players values('Gabriel', 5, 'Arsenal', 'Brazil', 'Defender');
insert into players values('Laurent Koscielny', 6, 'Arsenal', 'France', 'Defender');
insert into players values('Nacho Monreal', 18, 'Arsenal', 'Spain', 'Defender');
insert into players values('Hector Bellerin', 24, 'Arsenal', 'Spain', 'Defender');
insert into players values('Carl Jenkinson', 25, 'Arsenal', 'England', 'Defender');
insert into players values('Rob Holding', 16, 'Arsenal', 'England', 'Defender');
insert into players values('Shkodran Mustafi', 20, 'Arsenal', 'Germany', 'Defender');
insert into players values('Mesut Ozil', 11, 'Arsenal', 'Germany', 'Midfielder');
insert into players values('Alex Oxlade-Chamberlain', 15, 'Arsenal', 'England', 'Midfielder' );
insert into players values('Aaron Ramsey', 8, 'Arsenal', 'Wales', 'Midfielder');
insert into players values('Santiago Cazorla', 19, 'Arsenal', 'Spain', 'Midfielder');
insert into players values('Francis Coquelin', 34, 'Arsenal', 'France', 'Midfielder');
insert into players values('Mohamed Elneny', 35, 'Arsenal', 'Egypt', 'Midfielder');
insert into players values('Alex Iwobi', 17, 'Arsenal', 'Nigeria', 'Midfielder');
insert into players values('Granit Xhaka', 29, 'Arsenal', 'Switzerland', 'Midfielder');
insert into players values('Jeff Riene-Adelaide', 31, 'Arsenal', 'France', 'Midfielder');
insert into players values('Ben Sheaf', 65, 'Arsenal', 'England', 'Midfielder');
insert into players values('Chris Willock', 68, 'Arsenal', 'England', 'Midfielder');
insert into players values('Ainsley Maitland-Niles', 55, 'Arsenal', 'England', 'Midfielder');
insert into players values('Olivier Giroud', 12, 'Arsenal', 'France', 'Forward');
insert into players values('Theo Walcott', 14, 'Arsenal', 'England', 'Forward');
insert into players values('Alexis Sanchez', 7, 'Arsenal', 'Chile', 'Forward');
insert into players values('Yaya Sanogo', 22, 'Arsenal', 'France', 'Forward');
insert into players values('Danny Welbeck', 23, 'Arsenal', 'England', 'Forward');
insert into players values('Takuma Asano', 0, 'Arsenal', 'Japan', 'Forward');
insert into players values('Lucas Perez', 9, 'Arsenal', 'Spain', 'Forward');
insert into players values('Josh Da Silva', 41, 'Arsenal', 'England', 'Forward');

--  AFC Bournemouth
insert into players values('Adam Federici', 23, 'AFC Bournemouth', 'Australia', 'GoalKeeper');
insert into players values('Artur Boruc', 1, 'AFC Bournemouth', 'Poland', 'GoalKeeper');
insert into players values('Ryan Allsop', 21, 'AFC Bournemouth', 'England', 'GoalKeeper');
insert into players values('Simon Francis', 2, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Steve Cook', 3, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Charlie Daniels', 3, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Tyrone Mings', 26, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Adam Smith', 15, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Brad Smith', 14, 'AFC Bournemouth', 'Australia', 'Defender');
insert into players values('Corey Jordan', 37, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Ollie Harfield', 40, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Jack Simpson', 42, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Baily Cargill', 30, 'AFC Bournemouth', 'England', 'Defender');
insert into players values('Dan Gosling', 4, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Andrew Surman', 6, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Marc Pugh', 7, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Harry Arter', 8, 'AFC Bournemouth', 'Ireland', 'Midfielder');
insert into players values('Junior Stanislas', 19, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Lewis Cook', 18, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Jordan Ibe', 33, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Ryan Fraser', 24, 'AFC Bournemouth', 'Scotland', 'Midfielder');
insert into players values('Jack Wilshere', 32, 'AFC Bournemouth', 'England', 'Midfielder');
insert into players values('Keelan O''Connell', 52, 'AFC Bournemouth', 'England', 'Midfielder' );
insert into players values('Max Gradel', 10, 'AFC Bournemouth', 'Cote D''Ivoire', 'Forward');
insert into players values('Callum Wilson', 13, 'AFC Bournemouth', 'England', 'Forward');
insert into players values('Joshua King', 17, 'AFC Bournemouth', 'Norway', 'Forward');
insert into players values('Benik Afobe', 9, 'AFC Bournemouth', 'Congo', 'Forward');
insert into players values('Lys Mousset', 31, 'AFC Bournemouth', 'France', 'Forward');

--Burnley players
insert into players values('Tom Heaton', 1, 'Burnley', 'England', 'GoalKeeper');
insert into players values('Paul Robinson', 17, 'Burnley', 'England', 'GoalKeeper');
insert into players values('Nick Pope', 29, 'Burnley', 'England', 'GoalKeeper');
insert into players values('Matthew Lowton', 2, 'Burnley', 'England', 'Defender');
insert into players values('Ben Mee', 6, 'Burnley', 'England', 'Defender');
insert into players values('Stephen Ward', 23, 'Burnley', 'Ireland', 'Defender');
insert into players values('James Tarkowski', 26, 'Burnley', 'England', 'Defender');
insert into players values('Tendayi Darikwa', 27, 'Burnley', 'England', 'Defender');
insert into players values('Jon Flanagan', 4, 'Burnley', 'England', 'Defender');
insert into players values('Kevin Long', 28, 'Burnley', 'Ireland', 'Defender');
insert into players values('Michael Keane', 5, 'Burnley', 'England', 'Defender');
insert into players values('Dean Marney', 8, 'Burnley', 'England', 'Defender');
insert into players values('George Boyd', 21, 'Burnley', 'Scotland', 'Midfielder');
insert into players values('Scott Arfield', 37, 'Burnley', 'Canada', 'Midfielder');
insert into players values('Johann Berg Gudmundsson', 25, 'Burnley', 'Iceland', 'Midfielder');
insert into players values('Steven Defour', 16, 'Burnley', 'Belgium', 'Midfielder');
insert into players values('Jeff Hendrick', 13, 'Burnley', 'Ireland', 'Midfielder');
insert into players values('Joey Barton', 19, 'Burnley', 'England', 'Midfielder');
insert into players values('Robbie Brady', 12, 'Burnley', 'Ireland', 'Midfielder');
insert into players values('Ashley Westwood', 18, 'Burnley', 'England', 'Midfielder');
insert into players values('Andre Gray', 7, 'Burnley', 'England', 'Midfielder');
insert into players values('Sam Vokes', 9, 'Burnley', 'Wales', 'Midfielder');
insert into players values('Ashley Barnes', 10, 'Burnley', 'Austria', 'Midfielder');
insert into players values('Daniel Agyei', 32, 'Burnley', 'England', 'Midfielder');

--Chelsea players
insert into players values('Asmir Begovic', 1, 'Chelsea', 'Bosnia and Herzegovina', 'GoalKeeper');
insert into players values('Thibaut Courtois', 13, 'Chelsea', 'Belgium', 'GoalKeeper');
insert into players values('Eduardo', 37, 'Chelsea', 'Portugal', 'GoalKeeper');
insert into players values('Kurt Zouma', 5, 'Chelsea', 'France', 'Defender');
insert into players values('Gary Cahill', 24, 'Chelsea', 'England', 'Defender');
insert into players values('John Terry', 26, 'Chelsea', 'England', 'Defender');
insert into players values('Cesar Azpilicueta', 28, 'Chelsea', 'Spain', 'Defender');
insert into players values('Ola Aina', 34, 'Chelsea', 'England', 'Defender');
insert into players values('Marcos Alonso', 3, 'Chelsea', 'Spain', 'Defender');
insert into players values('David Luiz', 30, 'Chelsea', 'Brazil', 'Defender');
insert into players values('Nathan Ake', 6, 'Chelsea', 'Netherlands', 'Defender');
insert into players values('Cesc Fabergas', 4, 'Chelsea', 'Spain', 'Midfielder');
insert into players values('Eden Hazard', 10, 'Chelsea', 'Belgium', 'Midfielder');
insert into players values('Nemanja Matic', 21, 'Chelsea', 'Serbia', 'Midfielder');
insert into players values('William', 22, 'Chelsea', 'Brazil', 'Midfielder');
insert into players values('Ruben Loftus-Cheek', 14, 'Chelsea', 'England', 'Midfielder');
insert into players values('Victor Moses', 15, 'Chelsea', 'Nigeria', 'Midfielder');
insert into players values('N''Golo Kante', 7, 'Chelsea', 'France', 'Midfielder');
insert into players values('Nathaniel Chalobah', 29, 'Chelsea', 'England', 'Midfielder');
insert into players values('Pedro', 11, 'Chelsea', 'Spain', 'Forward');
insert into players values('Diego Costa', 19, 'Chelsea', 'Spain', 'Forward');
insert into players values('Michy Batshuayi', 23, 'Chelsea', 'Belgium', 'Forward');
insert into players values('Dominic Solanke', 41, 'Chelsea', 'England', 'Forward');
insert into players values('Kenedy', 0, 'Chelsea', 'Brazil', 'Forward');

--Crystal Palace players
insert into players values('Julian Speroni', 1, 'Crystal Palace', 'Argentina', 'GoalKeeper');
insert into players values('Wayne Hennessey', 13, 'Crystal Palace', 'Wales', 'GoalKeeper');
insert into players values('Steve Mandanda', 30, 'Crystal Palace', 'France', 'GoalKeeper');
insert into players values('Kleton Perntreou', 40, 'Crystal Palace', 'Greece', 'GoalKeeper');
insert into players values('Joel Ward', 2, 'Crystal Palace', 'England', 'Defender');
insert into players values('Scott Dann', 6, 'Crystal Palace', 'England', 'GoalKeeper');
insert into players values('Pape Souare', 23, 'Crystal Palace', 'Senegal', 'Defender');
insert into players values('Damien Delaney', 27, 'Crystal Palace', 'Ireland', 'Defender');
insert into players values('Martin Kelly', 34, 'Crystal Palace', 'England', 'Defender');
insert into players values('James Tomkins', 5, 'Crystal Palace', 'England', 'Defender');
insert into players values('Ezekiel Fryers', 19, 'Crystal Palace', 'England', 'Defender');
insert into players values('Ben Wynter', 44, 'Crystal Palace', 'England', 'Defender');
insert into players values('Michael Phillips', 45, 'Crystal Palace', 'England', 'Defender');
insert into players values('Patrick van Aanholt', 0, 'Crystal Palace', 'Netherlands', 'Defender');
insert into players values('Mamadou Sakho', 12, 'Crystal Palace', 'France', 'Defender');
insert into players values('Yohan Cabaye', 7, 'Crystal Palace', 'France', 'Midfielder');
insert into players values('Wilfried Zaha', 11, 'Crystal Palace', 'Cote D''Ivoire', 'Midfielder' );
insert into players values('Lee Chung-yong', 14, 'Crystal Palace', 'South Korea', 'Midfielder');
insert into players values('James McArthur', 18, 'Crystal Palace', 'Scotland', 'Midfielder');
insert into players values('Bakary Sako', 26, 'Crystal Palace', 'Mali', 'Midfielder');
insert into players values('Joe Ledley', 16, 'Crystal Palace', 'Wales', 'Midfielder');
insert into players values('Jason Puncheon', 42, 'Crystal Palace', 'England', 'Midfielder');
insert into players values('Andros Townsend', 10, 'Crystal Palace', 'England', 'Midfielder');
insert into players values('Mathieu Flamini', 4, 'Crystal Palace', 'France', 'Midfielder');
insert into players values('Luke Dreher', 35, 'Crystal Palace', 'England', 'Midfielder');
insert into players values('Aaron Wan-Bissaka', 46, 'Crystal Palace', 'England', 'Midfielder');
insert into players values('Sullay Kaikai', 25, 'Crystal Palace', 'England', 'Midfielder');
insert into players values('Jeffrey Schlupp', 31, 'Crystal Palace', 'Ghana', 'Midfielder');
insert into players values('Luka Milivojevic', 28, 'Crystal Palace', 'Serbia', 'Midfielder');
insert into players values('Fraizer Campbell', 9, 'Crystal Palace', 'England', 'Forward');
insert into players values('Connor Wickham', 21, 'Crystal Palace', 'England', 'Forward');
insert into players values('Christian Benteke', 17, 'Crystal Palace', 'Belgium', 'Forward');
insert into players values('Loic Remy', 8, 'Crystal Palace', 'France', 'Forward');
insert into players values('Jonathan Benteke', 15, 'Crystal Palace', 'Belgium', 'Forward');

--Everton players
insert into players values('Joel Robles', 1, 'Everton', 'Spain', 'GoalKeeper');
insert into players values('Chris Renshaw', 0, 'Everton', 'England', 'GoalKeeper');
insert into players values('Maarten Stekelenburg', 22, 'Everton', 'Netherlands', 'GoalKeeper');
insert into players values('Mateusz Hewelt', 41, 'Everton', 'Poland', 'GoalKeeper');
insert into players values('Leighton Baines', 3, 'Everton', 'England', 'Defender');
insert into players values('Phil Jagielka', 6, 'Everton', 'England', 'Defender');
insert into players values('Seamus Coleman', 23, 'Everton', 'Ireland', 'Defender');
insert into players values('Ramiro Funes Mori', 25, 'Everton', 'Argentina', 'Defender');
insert into players values('Ashley Williams', 5, 'Everton', 'Wales', 'Defender');
insert into players values('Mason Holgate', 30, 'Everton', 'England', 'Defender');
insert into players values('Jonjoe Kenny', 43, 'Everton', 'England', 'Defender');
insert into players values('Kevin Mirallas', 11, 'Everton', 'Belgium', 'Midfielder');
insert into players values('James McCarthy', 16, 'Everton', 'Ireland', 'Midfielder');
insert into players values('Muhamed Besic', 21, 'Everton', 'Bosnia and Herzegovina', 'Midfielder');
insert into players values('Gareth Barry', 18, 'Everton', 'England', 'Midfielder');
insert into players values('Ross Barkley', 8, 'Everton', 'England', 'Midfielder');
insert into players values('Idrissa Gueye', 17, 'Everton', 'Senegal', 'Midfielder');
insert into players values('Aaron Lennon', 12, 'Everton', 'England', 'Midfielder');
insert into players values('Tom Davies', 26, 'Everton', 'England', 'Midfielder');
insert into players values('Morgan Schneiderlin', 2, 'Everton', 'France', 'Midfielder');
insert into players values('Arouna Kone', 9, 'Everton', 'Cote D''Ivoire', 'Forward');
insert into players values('Romelu Lukaku', 10, 'Everton', 'Belgium', 'Forward');
insert into players values('Yannick Bolasie', 14, 'Everton', 'Congo', 'Forward');
insert into players values('Enner Valencia', 19, 'Everton', 'Ecuador', 'Forward');
insert into players values('Dominic Calvert-Lewin', 29, 'Everton', 'England', 'Forward');
insert into players values('Ademola Lookman', 31, 'Everton', 'England', 'Forward');

--Hull City players
insert into players values('Eldin Jakupovic', 16, 'Hull City', 'Switzerland', 'GoalKeeper');
insert into players values('William Mannion', 35, 'Hull City', 'England', 'GoalKeeper');
insert into players values('David Marshall', 23, 'Hull City', 'Scotland', 'GoalKeeper');
insert into players values('Curtis Davies', 6, 'Hull City', 'England', 'Defender');
insert into players values('Harry Maguire', 5, 'Hull City', 'England', 'Defender');
insert into players values('Michael Dawson', 21, 'Hull City', 'England', 'Defender');
insert into players values('Andrew Robertson', 3, 'Hull City', 'Scotland', 'Defender');
insert into players values('Brian Lenihan', 31, 'Hull City', 'Ireland', 'Defender');
insert into players values('Josh Tymon', 28, 'Hull City', 'England', 'Defender');
insert into players values('Ahmed Elmohamady', 27, 'Hull City', 'Egypt', 'Defender');
insert into players values('Omar Elabdellaoui', 14, 'Hull City', 'Norway', 'Defender');
insert into players values('Andrea Ranocchia', 13, 'Hull City', 'Italy', 'Defender');
insert into players values('Moses Odubajo', 2, 'Hull City', 'England', 'Midfielder');
insert into players values('David Meyler', 7, 'Hull City', 'Ireland', 'Midfielder');
insert into players values('Tom Huddlestone', 8, 'Hull City', 'England', 'Midfielder');
insert into players values('Sam Clucas', 11, 'Hull City', 'England', 'Midfielder');
insert into players values('Shaum Maloney', 15, 'Hull City', 'Scotland', 'Midfielder');
insert into players values('Greg Olley', 36, 'Hull City', 'England', 'Midfielder');
insert into players values('Ryan Mason', 25, 'Hull City', 'England', 'Midfielder');
insert into players values('Evandro', 40, 'Hull City', 'Brazil', 'Midfielder');
insert into players values('Lazar Markovic', 0, 'Hull City', 'Serbia', 'Midfielder');
insert into players values('Alfred N''Diaye', 10, 'Hull City', 'Senegal', 'Midfielder');
insert into players values('Kamil Grosicki', 17, 'Hull City', 'Poland', 'Midfielder');
insert into players values('Abel Hernandez', 9, 'Hull City', 'Uruguay', 'Midfielder');
insert into players values('Adama Diomande', 20, 'Hull City', 'Norway', 'Forward');
insert into players values('Greg Luer', 32, 'Hull City', 'England', 'Forward');
insert into players values('Ben Hinchcliffe', 39, 'Hull City', 'England', 'Forward');
insert into players values('Will Keane', 19, 'Hull City', 'England', 'Forward');
insert into players values('Dieumerci Mbokani', 18, 'Hull City', 'Congo', 'Forward');
insert into players values('Jarrod Bowen', 29, 'Hull City', 'England', 'Forward');
insert into players values('Oumar Niasee', 24, 'Hull City', 'Senegal', 'Forward');

--Leicester City players
insert into players values('Kasper Schmeichel', 1, 'Leicester City', 'Denmark', 'GoalKeeper');
insert into players values('Ben Hamer', 12, 'Leicester City', 'England', 'GoalKeeper');
insert into players values('Ron-Robert Zieler', 21, 'Leicester City', 'Germany', 'GoalKeeper');
insert into players values('Wes Morgan', 5, 'Leicester City', 'Jamaica', 'Defender');
insert into players values('Marcin Wasilewski', 27, 'Leicester City', 'Poland', 'Defender');
insert into players values('Danny Simpson', 17, 'Leicester City', 'England', 'Defender');
insert into players values('Christian Fuchs', 28, 'Leicester City', 'Austria', 'Defender');
insert into players values('Ben Chilwell', 3, 'Leicester City', 'England', 'Defender');
insert into players values('Robert Huth', 6, 'Leicester City', 'Germany', 'Defender');
insert into players values('Yohan Benalouane', 29, 'Leicester City', 'Tunisia', 'Defender');
insert into players values('Daniel Drinkwater', 4, 'Leicester City', 'England', 'Midfielder');
insert into players values('Andy King', 10, 'Leicester City', 'Wales', 'Midfielder');
insert into players values('Marc Albrighton', 11, 'Leicester City', 'England', 'Midfielder');
insert into players values('Daniel Amartey', 13, 'Leicester City', 'Ghana', 'Midfielder');
insert into players values('Riyad Mahrez', 26, 'Leicester City', 'Algeria', 'Midfielder');
insert into players values('Demarai Gray', 22, 'Leicester City', 'England', 'Midfielder');
insert into players values('Nampalys Mendy', 24, 'Leicester City', 'France', 'Midfielder');
insert into players values('Bartosz Kapustka', 14, 'Leicester City', 'Poland', 'Midfielder');
insert into players values('Wilfred Ndidi', 25, 'Leicester City', 'Nigeria', 'Midfielder');
insert into players values('Jamie Vardy', 9, 'Leicester City', 'England', 'Forward');
insert into players values('Shinji Okazaki', 20, 'Leicester City', 'Japan', 'Forward');
insert into players values('Leonardo Ulloa', 23, 'Leicester City', 'Argentina', 'Forward');
insert into players values('Ahmed Musa', 7, 'Leicester City', 'Nigeria', 'Forward');
insert into players values('Islam Slimani', 19, 'Leicester City', 'Algeria', 'Forward');

--Liverpool players
insert into players values('Simon Mignolet', 22, 'Liverpool', 'Belgium', 'GoalKeeper');
insert into players values('Loris Karius', 1, 'Liverpool', 'Germany', 'GoalKeeper');
insert into players values('Alexander Manninger', 13, 'Liverpool', 'Austria', 'GoalKeeper');
insert into players values('Nathaniel Clyne', 2, 'Liverpool', 'England', 'Defender');
insert into players values('Dejan Lovren', 6, 'Liverpool', 'Croatia', 'Defender');
insert into players values('Joseph Gomez', 12, 'Liverpool', 'England', 'Defender');
insert into players values('Alberto Moreno', 18, 'Liverpool', 'Spain', 'Defender');
insert into players values('Joel Matip', 32, 'Liverpool', 'Cameroon', 'Defender');
insert into players values('Ragnar Klavan', 17, 'Liverpool', 'Estonia', 'Defender');
insert into players values('Connor Randall', 56, 'Liverpool', 'England', 'Defender');
insert into players values('Tren Alexander-Arnold', 66, 'Liverpool', 'England', 'Defender');
insert into players values('Jordan Williams', 49, 'Liverpool', 'Wales', 'Defender');
insert into players values('James Milner', 7, 'Liverpool', 'England', 'Defender');
insert into players values('Philippe Coutinho', 10, 'Liverpool', 'Brazil', 'Midfielder');
insert into players values('Jordan Henderson', 14, 'Liverpool', 'England', 'Midfielder');
insert into players values('Adam Lallana', 20, 'Liverpool', 'England', 'Defender');
insert into players values('Lucas Leiva', 21, 'Liverpool', 'Brazil', 'Midfielder');
insert into players values('Emre Can', 23, 'Liverpool', 'Germany', 'Midfielder');
insert into players values('Sadio Mane', 19, 'Liverpool', 'Senegal', 'Midfielder' );
insert into players values('Georginio Wijnaldum', 5, 'Liverpool', 'Netherlands', 'Midfielder');
insert into players values('Kevin Stewart', 35, 'Liverpool', 'England', 'Midfielder');
insert into players values('Marko Grujic', 16, 'Liverpool', 'Serbia', 'Midfielder');
insert into players values('Sheyi Ojo', 54, 'Liverpool', 'England', 'Midfielder');
insert into players values('Ovie Ejaria', 53, 'Liverpool', 'England', 'Midfielder');
insert into players values('Ben Woodburn', 58, 'Liverpool', 'Wales', 'Midfielder');
insert into players values('Harry Wilson', 56, 'Liverpool', 'Wales', 'Midfielder');
insert into players values('Paulinho', 61, 'Liverpool', 'Portugal', 'Midfielder');
insert into players values('Roberto Firmino', 11, 'Liverpool', 'Brazil', 'Forward');
insert into players values('Daniel Sturridge', 15, 'Liverpool', 'England', 'Forward');
insert into players values('Divock Origi', 27, 'Liverpool', 'Belgium', 'Forward');
insert into players values('Danny Ings', 28, 'Liverpool', 'England', 'Forward');

--Manchester City players
insert into players values('Wily Caballero', 13, 'Manchester City', 'Argentina', 'GoalKeeper');
insert into players values('Angus Gunn', 54, 'Manchester City', 'England', 'GoalKeeper');
insert into players values('Claudio Bravo', 1, 'Manchester City', 'Chile', 'GoalKeeper');
insert into players values('Bacary Sagna', 3, 'Manchester City', 'France', 'Defender');
insert into players values('Vincent Kompany', 4, 'Manchester City', 'Belgium', 'Defender');
insert into players values('Pablo Zabaleta', 5, 'Manchester City', 'Argentina', 'Defender');
insert into players values('Aleksandar Kolarov', 11, 'Manchester City', 'Serbia', 'Defender');
insert into players values('Gael Clichy', 22, 'Manchester City', 'France', 'Defender');
insert into players values('Nicolas Otamendi', 30, 'Manchester City', 'Argentina', 'Defender');
insert into players values('John Stones', 24, 'Manchester City', 'England', 'Defender');
insert into players values('Tosin Adarabioyo', 53, 'Manchester City', 'England', 'Defender');
insert into players values('Fernando', 6, 'Manchester City', 'Brazil', 'Midfielder');
insert into players values('Jesus Navas', 15, 'Manchester City', 'Spain', 'Midfielder');
insert into players values('Kevin De Bruyne', 17, 'Manchester City', 'Belgium', 'Midfielder');
insert into players values('Fabian Delph', 18, 'Manchester City', 'England', 'Midfielder');
insert into players values('David Silva', 21, 'Manchester City', 'Spain', 'Midfielder');
insert into players values('Fernandinho', 25, 'Manchester City', 'Brazil', 'Midfielder');
insert into players values('Yaya Toure', 42, 'Manchester City', 'Cote D''Ivoire', 'Midfielder');
insert into players values('Ilkay Gundogan', 8, 'Manchester City', 'Germany', 'Midfielder');
insert into players values('Leroy Sane', 19, 'Manchester City', 'Germany', 'Midfielder');
insert into players values('Aleix Garcia', 75, 'Manchester City', 'Spain', 'Midfielder');
insert into players values('Brahim Diaz', 55, 'Manchester City', 'Spain', 'Midfielder');
insert into players values('Raheem Sterling', 7, 'Manchester City', 'England', 'Forward');
insert into players values('Sergio Aguero', 10, 'Manchester City', 'Argentina', 'Forward');
insert into players values('Kelechi Iheanacho', 72, 'Manchester City', 'Nigeria', 'Forward');
insert into players values('Nolito', 9, 'Manchester City', 'Spain', 'Forward');
insert into players values('Phil Foden', 80, 'Manchester City', 'England', 'Forward');
insert into players values('Gabriel Jesus', 33, 'Manchester City', 'Brazil', 'Forward');
  
