

insert into teams values('Manchester United',1878,'Old Trafford', 'Manchester United plc'

'David de Gea', 1, 'Manchester United', 'Spain', 'GoalKeeper'
'Sergio Romero', 20, 'Manchester United', 'Argentina', 'GoalKeeper'
'Joel Pereira', 40, 'Manchester United', 'Portugal', 'GoalKeeper'
'Dean Henderson', 34, 'Manchester United', 'England', 'GoalKeeper'
'Phil Jones', 4, 'Manchester United', 'England', 'Defender'
'Marcos Rojo', 5, 'Manchester United', 'Argentina', 'Defender'
'Chris Smalling', 12, 'Manchester United', 'England', 'Defender'
'Daley Blind', 17, 'Manchester United', 'Netherlands', 'Defender'
'Luke Shaw', 23, 'Manchester United', 'England', 'Defender'
'Antonio Valencia', 25, 'Manchester United', 'Ecuador', 'Defender'
'Matteo Darmian', 36, 'Manchester United', 'Italy', 'Defender'
'Timothy Fosu-Mensah', 24, 'Manchester United', 'Netherlands', 'Defender'
'Eric Bailly', 3, 'Manchester United', 'Cote DIvoire', 'Defender'
'Axel Tuanzebe', 38, 'Manchester United', 'England', 'Defender'
'Juan Mata', 8 , 'Manchester United', 'Spain', 'Midfielder'
'Michael Carrick', 16, 'Manchester United', 'England', 'Midfielder'
'Ashley Young',18 , 'Manchester United', 'England', 'Midfielder'
'Ander Herrera', 21, 'Manchester United', 'Spain', 'Midfielder'
'Marouane Fellaini', 27, 'Manchester United', 'Belgium', 'Midfielder'
'Jesse Lingard', 14, 'Manchester United', 'England', 'Midfielder'
'Henrikh Mkhitaryan', 22, 'Manchester United', 'Armenia', 'Midfielder'
'Paul Pogba', 6, 'Manchester United', 'France', 'Midfielder'
'Anthony Martial', 11, 'Manchester United', 'France', 'Forward'
'Wayne Rooney', 10, 'Manchester United', 'England', 'Forward'
'Marcus Rashford', 19, 'Manchester United', 'England', 'Forward'
'Zlatan Ibrahimovic', 9, 'Manchester United', 'Sweden', 'Forward'

insert into teams values ('Middlesbrough',1876, 'Riverside Stadium', 'Steve Gibson'

'Dimitrios Konstantopoulos', 1, 'Middlesbrough', 'Greece', 'GoalKeeper'
'Victor Valdes', 26, 'Middlesbrough', 'Spain', 'GoalKeeper'
'Brad Guzan', 12, 'Middlesbrough', 'United States', 'GoalKeeper'
'George Friend', 3, 'Middlesbrough', 'England', 'Defender'
'Daniel Ayala', 4, 'Middlesbrough', 'Spain', 'Defender'
'Ben Gibson', 6, 'Middlesbrough', 'England', 'Defender'
'Bernardo', 5, 'Middlesbrough', 'Colombia', 'Defender'
'Antonio Barragan', 17, 'Middlesbrough', 'Spain', 'Defender'
'Fabio', 2, 'Middlesbrough', 'Brazil', 'Defender'
'James Husband', 40, 'Middlesbrough', 'England', 'Defender'
'Calum Chambers', 25, 'Middlesbrough', 'England', 'Defender'
'Dael Fry', 22, 'Middlesbrough', 'England', 'Defender'
'Grant Leadbitter', 7, 'Middlesbrough', 'England', 'Midfielder'
'Adam Clayton', 8, 'Middlesbrough', 'England', 'Midfielder'
'Stewart Downing', 19, 'Middlesbrough', 'England', 'Midfielder'
'Adam Forshaw', 34, 'Middlesbrough', 'England', 'Midfielder'
'Marten de Roon', 14, 'Middlesbrough', 'Netherlands', 'Midfielder'
'Adama Traore', 37, 'Middlesbrough', 'Spain', 'Midfielder'
'Gaston Ramirez', 21, 'Middlesbrough', 'Uruguay', 'Midfielder'
'Adlene Guedioura', 27, 'Middlesbrough', 'Algeria', 'Midfielder'
'Cristhian Stuani', 18, 'Middlesbrough', 'Uruguay', 'Forward'
'Viktor Fischer', 11, 'Middlesbrough', 'Denmark', 'Forward'
'Alvaro Negredo', 10, 'Middlesbrough', 'Spain', 'Forward'
'Rudy Gestede', 29, 'Middlesbrough', 'Benin', 'Forward'

insert into teams values ('Southampton', 1885, 'St Mary\'s Stadium', 'Katharina Liebherr'

'Fraser Forster',1,'Southampton','England','GoalKeeper'
'Alex McCarthy',13,'Southampton','England','GoalKeeper'
'Stuart Taylor',28,'Southampton','England','GoalKeeper'
'Harry Lewis',41,'Southampton','England','GoalKeeper'
'Mouez Hassen',40,'Southampton','France','GoalKeeper'
'Cedric Soares',2,'Southampton','Portugal','Defender'
'Maya Yoshida',3,'Southampton','Japan','Defender'
'Florin Gardos',5,'Southampton','Romania','Defender'
'Cuco Martina',15,'Southampton','Curacao','Defender'
'Virgil van Dijk',17,'Southampton','Netherlands','Defender'
'Matt Targett',33,'Southampton','England','Defender'
'Jeremy Pied',26,'Southampton','France','Defender'
'Jack Stephens'24,,'Southampton','England','Defender'
'Ryan Bertrand',21,'Southampton','England','Defender'
'Martin Caceres',12,'Southampton','Uruguay','Defender'
'Jordy Clasie',4,'Southampton','Netherlands','Midfielder'
'Steven Davis',8,'Southampton','Northern Ireland','Midfielder'
'usan Tadic',11,'Southampton','Serbia','Midfielder'
'Oriol Romeu',14,'Southampton','Spain','Midfielder'
'James Ward-Prowse',16,'Southampton','England','Midfielder'
'Harrison Reed',18,'Southampton','England','Midfielder'
'Nathan Redmond',22,'Southampton','England','Midfielder'
'Pierre-Emile Hojbjerg',23,'Southampton','Denmark','Midfielder'
'Sofiane Boufal',19,'Southampton','Morocco','Midfielder'
'Lloyd Isgrove',27,'Southampton','Wales','Midfielder'
'Jake Hesketh',42,'Southampton','England','Midfielder'
'Sam McQueen',38,'Southampton','England','Midfielder'
'Josh Sims',39,'Southampton','England','Midfielder'
'Shane Long',7,'Southampton','Ireland','Forward'
'Jay Rodriquez',9,'Southampton','England','Forward'
'Charlie Austin',10,'Southampton','England','Forward'
'Olufela Olomola',32,'Southampton','Nigeria','Forward'
'Manolo Gabbiadini',20,'Southampton','Italy','Forward'

insert into teams values ('Stoke City', 1863, 'bet365 Stadium', 'bet365'

'Jack Butland',1,'Stoke City','England','GoalKeeper'
'Shay Given',24,'Stoke City','Ireland','GoalKeeper'
'Daniel Bachmann',35,'Stoke City','Austria','GoalKeeper'
'Phil Bardsley',2,'Stoke City','Scotland','Defender'
'Erik Pieters',3,'Stoke City','Netherlands','Defender'
'Marc Muniesa',5,'Stoke City','Spain','Defender'
'Glen Johnson',8,'Stoke City','England','Defender'
'Ryan Shawcross',17,'Stoke City','England','Defender'
'Geoff Cameron',20,'Stoke City','United States','Defender'
'Bruno Martins Indi',15,'Stoke City','Netherlands','Defender'
'Thomas Edwards',72,'Stoke City','England','Defender'
'Glenn Whelan',6,'Stoke City','Ireland','Midfielder'
'Stephen Ireland',7,'Stoke City','Ireland','Midfielder'
'Ibrahim Afellay',14,'Stoke City','Netherlands','Midfielder'
'Charlie Adam',16,'Stoke City','Scotland','Midfielder'
'Giannelli Imbula',21,'Stoke City','France','Midfielder'
'Xherdan Shaqiri',22,'Stoke City','Switzerland','Midfielder'
'Ramadan Sobhi',32,'Stoke City','Egypt','Midfielder'
'Joe Allen',4,'Stoke City','Wales','Midfielder'
'Marko Arnautovic',10,'Stoke City','Austria','Forward'
'Mame Biram Diouf',18,'Stoke City','Senegal','Forward'
'Jonathan Walters',19,'Stoke City','Ireland','Forward'
'Peter Crouch',25,'Stoke City','England','Forward'
'Julien Ngoy',45,'Stoke City','Belgium','Forward'
'Wilfried Bony',12,'Stoke City','Cote DIvoire','Forward'
'Thibaud Verlinden',55,'Stoke City','Belgium','Forward'


insert into teams values ('Sunderland', 1879, 'Stadium of Light', 'Ellis Short'

'Jordan Pickford',13,'Sunderland','England','GoalKeeper'
'Vito Mannone',1,'Sunderland','Italy','GoalKeeper'
'Max Stryjek',32,'Sunderland','Poland','GoalKeeper'
'Mika',12,'Sunderland','Portugal','GoalKeeper'
'Billy Jones',2,'Sunderland','England','Defender'
'John OShea',16,'Sunderland','Ireland','Defender'
'Lamine Kone',23,'Sunderland','Cote DIvoire','Defender'
'Papy Dijilobodji',,'Sunderland','Senegal','Defender'
'Donald Love',22,'Sunderland','Scotland','Defender'
'Paddy McNair',19,'Sunderland','Northern Ireland','Defender'
'Javier Manquillo',21,'Sunderland','Spain','Defender'
'Josh Robson',45,'Sunderland','England','Defender'
'Jason Denayer',4,'Sunderland','Belgium','Defender'
'Joleon Lescott',15,'Sunderland','England','Defender'
'Bryan Oviedo',3,'Sunderland','Costa Rica','Defender'
'Jan Kirchhoff',27,'Sunderland','Germany','Midfielder'
'Sebastian Larsson',7,'Sunderland','Sweden','Midfielder'
'Lee Cattermole',6,'Sunderland','England','Midfielder'
'Jack Rodwell',8,'Sunderland','England','Midfielder'
'Wahbi Khazri',10,'Sunderland','Tunisia','Midfielder'
'Adnan Januzaj',44,'Sunderland','Belgium','Midfielder'
'Steven Pienaar',20,'Sunderland','South Africa','Midfielder'
'Lynden Gooch',46,'Sunderland','United States','Midfielder'
'Ethan Robson',25,'Sunderland','England','Midfielder'
'Rees Greenwood',37,'Sunderland','England','Midfielder'
'George Honeyman',39,'Sunderland','England','Midfielder'
'Didier Ndong',17,'Sunderland','Gabon','Midfielder'
'Elliot Embleton',40,'Sunderland','England','Midfielder'
'Fabio Borini',9,'Sunderland','Italy','Forward'
'Jermain Defoe',18,'Sunderland','England','Forward'
'Duncan Watmore',14,'Sunderland','England','Forward'
'Joel Asoro',29,'Sunderland','Sweden','Forward'
'Victor Anichebe',28,'Sunderland','Nigeria','Forward'
'Josh Maja',35,'Sunderland','England','Forward'


insert into teams values ('Swansea City', 1912, 'Liberty Stadium', 'Jason Levien'

'Jordan Ayew',3,'Swansea City','Ghana','Forward'
'Oliver McBurnie',62,'Swansea City','Scotland','Forward'
'Fernando Llorente',9,'Swansea City','Spain','Forward'
'Borja Baston',10,'Swansea City','Spain','Forward'
'Lukasz Fabianski',1,'Swansea City','Poland','GoalKeeper'
'Kristoffer Nordfeldt',13,'Swansea City','Sweden','GoalKeeper'
'Mark Birighitti',19,'Swansea City','Australia','GoalKeeper'
'Gerhard Tremmel',25,'Swansea City','Germany','GoalKeeper'
'Jordi Amat',2,'Swansea City','Spain','Defender'
'Angel Rangel',22,'Swansea City','Spain','Defender'
'Kyle Naughton',26,'Swansea City','England','Defender'
'Federico Fernandez',33,'Swansea City','Argentina','Defender'
'Mike van der Hoorn',5,'Swansea City','Netherlands','Defender'
'Alfie Mawson',6,'Swansea City','England','Defender'
'Stephen Kingsley',35,'Swansea City','Scotland','Defender'
'Martin Olsson',16,'Swansea City','Sweden','Defender'
'Connor Roberts',24,'Swansea City','Wales','Defender'
'Ki Sung-yueng',4,'Swansea City','South Korea','Midfielder'
'Leon Britton',7,'Swansea City','England','Midfielder'
'Nathan Dyer',12,'Swansea City','England','Midfielder'
'Wayne Routledge',15,'Swansea City','England','Midfielder'
'Jefferson Montero',20,'Swansea City','Ecuador','Midfielder'
'Gylfi Sigurdsson',23,'Swansea City','Iceland','Midfielder'
'Jack Cork',24,'Swansea City','England','Midfielder'
'Jay Fulton',56,'Swansea City','Scotland','Midfielder'
'Leroy Fer',8,'Swansea City','Netherlands','Midfielder'
'Daniel James',51,'Swansea City','Wales','Midfielder'
'Luciano Narsingh',28,'Swansea City','Netherlands','Midfielder'
'Tom Carroll',42,'Swansea City','England','Midfielder'


insert into teams values('Tottenham Hotspur',1882,'White Hart Lane', 'ENIC International Ltd.'

'Hugo Lloris',1,'Tottenham Hotspur','France','GoalKeeper'
'Michel Vorm',13,'Tottenham Hotspur','Netherlands','GoalKeeper'
'Pau Lopez',30,'Tottenham Hotspur','Spain','GoalKeeper'
'Alfie Whiteman',41,'Tottenham Hotspur','England','GoalKeeper'
'Kyle Walker',2,'Tottenham Hotspur','England','Defender'
'Danny Rose',3,'Tottenham Hotspur','England','Defender'
'Toby Alderweireld',4,'Tottenham Hotspur','Belgium','Defender'
'Jan Vertonghen',5,'Tottenham Hotspur','Belgium','Defender'
'Kieran Trippier',16,'Tottenham Hotspur','England','Defender'
'Kevin Wimmer',27,'Tottenham Hotspur','Austria','Defender'
'Ben Davis',33,'Tottenham Hotspur','Wales','Defender'
'Cameron Carter-Vickers',38,'Tottenham Hotspur','United States','Defender'
'Kyle Walker-Peters',37,'Tottenham Hotspur','England','Defender'
'Son Heung-Min',7,'Tottenham Hotspur','South Korea','Midfielder'
'Erik Lamela',11,'Tottenham Hotspur','Argentina','Midfielder'
'Eric Dier',15,'Tottenham Hotspur','England','Midfielder'
'Mousa Dembele',19,'Tottenham Hotspur','Belgium','Midfielder'
'Dele Alli',20,'Tottenham Hotspur','England','Midfielder'
'Victor Wanyama',12,'Tottenham Hotspur','Kenya','Midfielder'
'Christian Eriksen',23,'Tottenham Hotspur','Denmark','Midfielder'
'Josh Onomah',25,'Tottenham Hotspur','England','Midfielder'
'Harry Winks',29,'Tottenham Hotspur','England','Midfielder'
'Moussa Sissoko',17,'Tottenham Hotspur','France','Midfielder'
'Georges-Kevin Nkoudou',14,'Tottenham Hotspur','France','Midfielder'
'Marcus Edwards',48,'Tottenham Hotspur','England','Midfielder'
'Harry Kane',10,'Tottenham Hotspur','England','Forward'
'Vincent Janssen',9,'Tottenham Hotspur','Netherlands','Forward'


insert into teams values ('Watford', 1881, 'Vicarage Road', 'Gino Pozzo'

'Heurelho Gomes',1,'Watford','Brazil','GoalKeeper'
'Costel Pantilimon',30,'Watford','Romania','GoalKeeper'
'Giedrius Arlauskis',34,'Watford','Lithuania','GoalKeeper'
'Rene Gilmartin',13,'Watford','Ireland','GoalKeeper'
'Miguel Britos',3,'Watford','Uruguay','Defender'
'Sebastian Prodl',5,'Watford','Austria','Defender'
'Craig Cathcart',15,'Watford','Northern Ireland','Defender'
'Jose Holebas',25,'Watford','Greece','Defender'
'Christian Kabasele',27,'Watford','Belgium','Defender'
'Juan Zuniga',18,'Watford','Colombia','Defender'
'Brice Dja Djedje',26,'Watford','Cote DIvoire','Defender'
'Younes Kaboul',4,'Watford','France','Defender'
'Daryl Janmaat',22,'Watford','Netherlands','Defender'
'Adrian Mariappa',6,'Watford','Jamaica','Defender'
'Andrew Eleftheriou',42,'Watford','Cyprus','Defender'
'Brandon Mason',32,'Watford','England','Defender'
'Charlie Rowan',38,'Watford','England','Defender'
'Abdoulaye Doucoure',16,'Watford','France','Midfielder'
'Valon Behrami',11,'Watford','Switzerland','Midfielder'
'Nordin Amrabat',7,'Watford','Morocco','Midfielder'
'Ben Watson',23,'Watford','England','Midfielder'
'Etienne Capoue',29,'Watford','France','Midfielder'
'Roberto Pereyra',37,'Watford','Argentina','Midfielder'
'Carl Stewart',35,'Watford','England','Midfielder'
'Tom Cleverley',8,'Watford','England','Midfielder'
'Troy Deeney',9,'Watford','England','Forward'
'Isaac Success',10,'Watford','Nigeria','Forward'
'Stefano Okaka',33,'Watford','Italy','Forward'
'MBaye Niang',21,'Watford','France','Forward'
'Mauro Zarate',20,'Watford','Argentina','Forward'


insert into teams values ('West Bromwich Albion', 1878, 'The Hawthorns', 'Guochuan Lai'

'Ben Foster',1,'West Bromwich Albion','England','GoalKeeper'
'Boaz Myhill',13,'West Bromwich Albion','Wales','GoalKeeper'
'Jack Rose',38,'West Bromwich Albion','England','GoalKeeper'
'Jonny Evans',6,'West Bromwich Albion','Northern Ireland','Defender'
'Gareth McAuley',23,'West Bromwich Albion','Northern Ireland','Defender'
'Craig Dawson',25,'West Bromwich Albion','England','Defender'
'Kane Wilson',49,'West Bromwich Albion','England','Defender'
'Brendan Galloway',20,'West Bromwich Albion','England','Defender'
'Nyom',2,'West Bromwich Albion','Cameroon','Defender'
'Marc Wilson',12,'West Bromwich Albion','Ireland','Defender'
'Claudio Yacob',5,'West Bromwich Albion','Argentina','Midfielder'
'James Morrison',7,'West Bromwich Albion','Scotland','Midfielder'
'Chris Brunt',11,'West Bromwich Albion','Northern Ireland','Midfielder'
'James McClean',14,'West Bromwich Albion','Ireland','Midfielder'
'Darren Fletcher',24,'West Bromwich Albion','Scotland','Midfielder'
'Jonathan Leko',45,'West Bromwich Albion','England','Midfielder'
'Matt Phillips',10,'West Bromwich Albion','Scotland','Midfielder'
'Sam Field',47,'West Bromwich Albion','England','Midfielder'
'Nacer Chadli',22,'West Bromwich Albion','Belgium','Midfielder'
'Rekeem Harper',34,'West Bromwich Albion','England','Midfielder'
'Salomon Rondon',9,'West Bromwich Albion','Venezuela','Forward'
'Hal Robson-Kanu',4,'West Bromwich Albion','Wales','Forward'




insert into teams values ('West Ham United', 1895, 'London Stadium', 'David Sullivan'

'Darren Randolph',1,'West Ham United','Ireland','GoalKeeper'
'Adrian',13,'West Ham United','Spain','GoalKeeper'
'Raphael Spiegel',34,'West Ham United','Switzerland','GoalKeeper'
'Winston Reid',2,'West Ham United','New Zealand','Defender'
'Aaron Cresswell',3,'West Ham United','England','Defender'
'James Collins',19,'West Ham United','Wales','Defender'
'Angelo Ogbonna',21,'West Ham United','Italy','Defender'
'Sam Byram',22,'West Ham United','England','Defender'
'Arthur Masuaku',26,'West Ham United','France','Defender'
'Alvaro Arbeloa',5,'West Ham United','Spain','Defender'
'Doneil Henry',25,'West Ham United','Canada','Defender'
'Jose Fonte',23,'West Ham United','Portugal','Defender'
'Cheikhou Kouyate',8,'West Ham United','Senegal','Midfielder'
'Pedro Obiang',14,'West Ham United','Spain','Midfielder'
'Mark Noble',16,'West Ham United','England','Midfielder'
'Michail Antonio',30,'West Ham United','England','Midfielder'
'Havard Nordtveit',4,'West Ham United','Norway','Midfielder'
'Sofiane Feghouli',7,'West Ham United','Algeria','Midfielder'
'Gokhan Tore',17,'West Ham United','Turkey','Midfielder'
'Edimilson Fernandes',31,'West Ham United','Switzerland','Midfielder'
'Grady Diangana',55,'West Ham United','England','Midfielder'
'Manuel Lanzini',10,'West Ham United','Argentina','Midfielder'
'Domingos Quina',36,'West Ham United','Portugal','Midfielder'
'Declan Rice',41,'West Ham United','Ireland','Midfielder'
'Robert Snodgrass',11,'West Ham United','Scotland','Midfielder'
'Andy Carroll',9,'West Ham United','England','Forward'
'Diafra Sakho',15,'West Ham United','Senegal','Forward'
'Andre Ayew',20,'West Ham United','Ghana','Forward'
'Jonathan Calleri',28,'West Ham United','Argentina','Forward'
'Ashley Fletcher',24,'West Ham United','England','Forward'












