'Hugo Lloris',1,'Tottenham Hotspur','France','GoalKeeper'
'Michel Vorm',13,'Tottenham Hotspur','Netherlands','GoalKeeper'
'Pau Lopez',30,'Tottenham Hotspur','Spain','GoalKeeper'
'Alfie Whiteman',41,'Tottenham Hotspur','England','GoalKeeper'
'Kyle Walker',2,'Tottenham Hotspur','England','Defender'
'Danny Rose',3,'Tottenham Hotspur','England','Defender'
'Toby Alderweireld',4,'Tottenham Hotspur','Belgium','Defender'
'Jan Vertonghen',5,'Tottenham Hotspur','Belgium','Defender'
'Kieran Trippier',16,'Tottenham Hotspur','England','Defender'
'Kevin Wimmer',27,'Tottenham Hotspur','Austria','Defender'
'Ben Davis',33,'Tottenham Hotspur','Wales','Defender'
'Cameron Carter-Vickers',38,'Tottenham Hotspur','United States','Defender'
'Kyle Walker-Peters',37,'Tottenham Hotspur','England','Defender'
'Son Heung-Min',7,'Tottenham Hotspur','South Korea','Midfielder'
'Erik Lamela',11,'Tottenham Hotspur','Argentina','Midfielder'
'Eric Dier',15,'Tottenham Hotspur','England','Midfielder'
'Mousa Dembele',19,'Tottenham Hotspur','Belgium','Midfielder'
'Dele Alli',20,'Tottenham Hotspur','England','Midfielder'
'Victor Wanyama',12,'Tottenham Hotspur','Kenya','Midfielder'
'Christian Eriksen',23,'Tottenham Hotspur','Denmark','Midfielder'
'Josh Onomah',25,'Tottenham Hotspur','England','Midfielder'
'Harry Winks',29,'Tottenham Hotspur','England','Midfielder'
'Moussa Sissoko',17,'Tottenham Hotspur','France','Midfielder'
'Georges-Kevin Nkoudou',14,'Tottenham Hotspur','France','Midfielder'
'Marcus Edwards',48,'Tottenham Hotspur','England','Midfielder'
'Harry Kane',10,'Tottenham Hotspur','England','Forward'
'Vincent Janssen',9,'Tottenham Hotspur','Netherlands','Forward'